version: '3.10'

services:
  db:
    image: postgres:latest
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGUSER=${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-p', '${POSTGRES_PORT}', '-U', '${POSTGRES_USER}', '-d', '${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
          - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - ./database/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

  app:
    build: .
    depends_on:
      - db
